apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blog-monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-blog
  template:
    metadata:
      labels:
        app: flask-blog
    spec:
      containers:
        - name: flask-blog
          image: varadpoddar/flask_blog:latest
          ports:
            - containerPort: 5000   
