apiVersion: v1
kind: Service
metadata:
  name: flask-blog-service
spec:
  type: NodePort
  selector:
    app: flask-blog
  ports:
    - port: 80
      targetPort: 5000   # again, match your container port
      nodePort: 30080    # NodePort in kind cluster